on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.1327+256ab68a9 # default is master
      - run: zig build
      - uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: wormhole-${{matrix.os}} # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: "./zig-out/bin/wormhole*"
