on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.1513+77bc8e7b6 # default is master
      - run: zig build
      - run: zig build -Dtarget=x86_64-windows-gnu
      - uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: wormhole # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
                ./zig-out/bin/wormhole
                ./zig-out/bin/wormhole.exe
